### ISSUE TITLE
Heroku deployment failing

### ISSUE THREAD

**Issue by Floppy** [theodi/bothan#276]
Due to the addition of `commonmarker` in #267, Heroku deployment is failing. `commonmarker` requires `cmake`, which isn't available by default on Heroku for some reason. We need to look at upgrading the stack, or adding a buildpack to get it.

It should be there by default on Ubuntu though, so this is a bit odd.

**Comment by quadrophobiac** [comment]
Thanks for looking into this @Floppy - really weird that cmake is a hassle on Heroku no?

**Comment by quadrophobiac** [comment]
is this pertinent https://github.com/gjtorikian/commonmarker/blob/master/.travis.yml?

**Comment by Floppy** [comment]
No, we're OK on travis.

**Comment by quadrophobiac** [comment]
I'm wondering now if this fail is due to the changes I made to the .travis in #269. It went from 
```
addons:
  apt:
    packages:
    - cmake
```

to

```
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
      - cmake
```

I'm wondering if specifying a specific ubuntu distro might be causing the `cmake` conflict?

Aside from that I'm wondering what possible resolutions/workarounds are available?
